#!/usr/bin/ruby
require 'net/https'
L=50
TOKEN=''
https=Net::HTTP.new('game.coderunner.jp',443)
https.use_ssl=true
https.start{
	#ランダムでスコアの良かったものから8文字シードを選ぶ
	#'AABCABDBADDDACCCADCCBAAABAAACDBAABCBBDAADDABABABAC'.chars.each_cons(8){|e|
	#6組選んで、つなぎ方をすべて試して残りも辞書に入ることを期待する
	['AADBACCB','DDDBDBCD','DCBCDBAABC','BAAADCCC','DCDCAAAD','BBDADDCC'].permutation{|e|
		s=e.join
		s=s[0,L]
		puts s
		resp=https.get("/q?token="+TOKEN+"&str="+s)
		redo if resp.code.to_i!=200
		puts resp.body
		sleep(1)
	}
}
__END__
[repeats]
A 1
B 1
C 2
D 2
AA 4
AAA 6
BB 3
BBB 8
BBBB 22
CC 5
CCC 11
DD 6
DDD 10

[good random]
CBBBCBABACBACBCBBDBDDCBADAACBCBBDBABCBADAAADBACCBD
971
DDDBDBCDCBBCABADABBDBBBDAAACBADDACBACACCBDCBBCDAAB
1007
CCCBABCDCDDBCBCDDCBACCBDBDDCBCDBAABCDADBBCBDAABCBB
1177
CBBAAADCCCABCACCDBCCBDBDADACBDBAACBADAAABADCDDCCBD
1046
BCADCDCAAADCACCADAADCDBCBBBACCBCCAAAABDBDCBDCADDDC
1056
DDADBABCCADDDBDBCBBBBDCAABABBBBCBABACCBABBDBBDADDC
996

BBAADDACACABDDCBBBDBACBBABBBADCADDBBDADDCCBBAAAACC
1120
BBCCADCCCCABAAABDCDADBDAACCBBCBAAAABBABBBABDDADDBB
1018
BCADCDCAAADCACCADAADCDBCBBBACCBCCAAAABDBDCBDCADDDC
1056
AABCABDBADDDACCCADCCBAAABAAACDBAABCBBDAADDABABABAC
1000

[good seeds]
AADBACCB
339
DDDBDBCD
251
DCBCDBAABC
313
262
269
BAAADCCC
328
DCDCAAAD
306
ABBDBBDA
234

BBDADDCC
388
CDBAABCB
298

[result]
AADBACCBDDDBDBCDABBDBBDADCBCDBAABCBAAADCCCDCDCAAAD
2392
AADBACCBABBDBBDADCBCDBAABCBAAADCCCDCDCAAADDDDBDBCD
2409
DDDBDBCDDCBCDBAABCBAAADCCCDCDCAAADABBDBBDAAADBACCB
2425
DCBCDBAABCBAAADCCCDCDCAAADABBDBBDAAADBACCBDDDBDBCD
2471
AADBACCBDDDBDBCDDCBCDBAABCBAAADCCCDCDCAAADBBDADDCC
2490
AADBACCBBAAADCCCDCDCAAADDDDBDBCDDCBCDBAABCBBDADDCC
2527